feat: pattern
TroyTae/game-of-life pull request #1078
Opened 2020-08-27 00:12 UTC by khabiirk

resolve #1074

2020-08-27 00:19 UTC, khabiirk commented
Hi, I can't seem to be able to start the dev server even locally. It keeps stopping because of errors.

2020-08-28 02:31 UTC, TroyTae requested changes

2020-08-28 02:31 UTC, TroyTae commented on src/life/oscillator/ellison-p4-HW-emulator.json
> +
Please remove this line

2020-08-28 02:32 UTC, TroyTae commented
> Hi, I can't seem to be able to start the dev server even locally. It keeps stopping because of errors.

Can you attach the error?

2020-08-28 02:53 UTC, khabiirk commented
<img width="1440" alt="Screenshot 2020-08-27 at 22 52 45" src="https://user-images.githubusercontent.com/63027274/91515844-13adb880-e8b8-11ea-890b-02a36fc4e27a.png">

2020-08-28 02:56 UTC, khabiirk commented on src/life/oscillator/ellison-p4-HW-emulator.json
> +
you mean line 13 ?

2020-08-28 03:11 UTC, TroyTae commented on src/life/oscillator/ellison-p4-HW-emulator.json
> +
No 14 line, because prettier not allow empty line.

2020-08-28 05:51 UTC, TroyTae commented
@khabiirk 
Thank you for finding that bug!
Now I push the fixed commit.

2020-08-29 05:47 UTC, TroyTae approved these changes
LGTM
Thank you for your contribution :)

2020-08-29 05:48 UTC, merged