feat: P200 traffic jam #1363
TroyTae/game-of-life pull request #1366
Opened 2020-11-10 15:36 UTC by EricWithC

resolve #1363

2020-11-11 03:11 UTC, TroyTae requested changes

2020-11-11 03:11 UTC, TroyTae commented on life/oscillator/p200-traffic-jam.json
> +
Can you remove these empty lines?

2020-11-11 13:25 UTC, EricWithC commented on life/oscillator/p200-traffic-jam.json
> +
Done

2020-11-12 14:57 UTC, TroyTae approved these changes
LGTM
Thank you for your contribution :)

2020-11-12 14:58 UTC, merged